import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Programming in Data Science 11521</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <nav>
          <Link href='/Week1/Week1'><a>Week 1</a></Link>
          <Link href='/Week2/Week2'><a>Week 2</a></Link>
          <Link href='/Week3/Week3'><a>Week 3</a></Link>
          <Link href='/Week4/Week4'><a>Week 4</a></Link>
        </nav>
        <h1 className={styles.title}>
          Welcome to Programming in Data Science 11521
        </h1>

        <p>Hello World</p>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
        </a>
      </footer>
    </div>
  );
};

export default Home;
